# Generated by Django 6.0.5 on 2026-07-30 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcomments',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_news_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
