# Generated by Django 6.0.5 on 2026-08-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_announcementcomments_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_new_aufgaben_list_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
